#!/bin/bash

# These aliases and functions have been added by aaronfranke's Linux-tools

# Export useful environment variables
export GPG_TTY=$(tty)

# Aliases for simple common commands
alias butler="$HOME/.config/itch/apps/butler/butler"
alias cstabs="find . -name '*.cs' -exec sed -i -e 's/    /\t/g' {} \;"
alias tscnnoeditor="find . -name '*.tscn' -exec sed -i '/^editor\//d' {} \;" # Remove "editor/display_folded"
alias extract="tar -xf"
alias la="ls -la"
alias ll="ls -l"
alias lookfor="grep -RIni"
alias nani='echo "Omae wa mou shindeiru" && sleep 3s && nano'
alias fuck='sudo $(history -p !!)'
alias redo='sudo $(history -p !!)'
alias sdd="sudo dcfldd" # Replaces "sudo dd", requires "dcfldd" to be installed.

# Functions for more complex operations. Most are just for mass-converting audio.
acid() {
    NUMBER=1.0
    while true; do
        NUMBER=$(echo "($NUMBER + 2.99) % 10 - 3" | bc)
        sleep 0.01
        xrandr --output LVDS --brightness $NUMBER
    done
}

format() {
    find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\)' -exec clang-format -style=file -i {} \;
}

recursive() {
    find . -type f -exec "$*" {} \;
}

fetchall() {
    cd "$HOME/workspace"
    for i in *; do
        cd "$HOME/workspace/$i"
        pwd
        git fetch --all
    done
}

replaceall() {
    find . -name "*.$1" -exec sed -i -e "s/$2/$3/g" {} \;
}

releasemouse() {
    setxkbmap -option grab:break_actions
    xdotool key XF86Ungrab
}

mp3ogg() {
    for i in *.mp3; do
        name=`echo $i | cut -d'.' -f1`
        echo "Converting ${name}.mp3 "
        ffmpeg -y -i "$i" -vn "${name}.ogg" 2> /dev/null
    done
    echo "Done! "
}

m4aogg() {
    for i in *.m4a; do
        name=`echo $i | cut -d'.' -f1`
        echo "Converting ${name}.m4a "
        ffmpeg -y -i "$i" -vn "${name}.ogg" 2> /dev/null
    done
    echo "Done! "
}

mkvogg() {
    for i in *.mkv; do
        name=`echo $i | cut -d'.' -f1`
        echo "Converting ${name}.mkv "
        ffmpeg -y -i "$i" -vn "${name}.ogg" 2> /dev/null
    done
    echo "Done! "
}

wavogg() {
    for i in *.wav; do
        name=`echo $i | cut -d'.' -f1`
        echo "Converting ${name}.wav "
        ffmpeg -y -i "$i" -vn "${name}.ogg" 2> /dev/null
    done
    echo "Done! "
}

opusogg() {
    for i in *.opus; do
        name=`echo $i | cut -d'.' -f1`
        echo "Converting ${name}.opus "
        ffmpeg -y -i "$i" -vn "${name}.ogg" 2> /dev/null
    done
    echo "Done! "
}

webmopus() {
    for i in *.webm; do
        name=`echo $i | cut -d'.' -f1`
        echo "Converting ${name}.webm "
        ffmpeg -y -i "$i" -vn -c:a copy "${name}.opus" 2> /dev/null
    done
    echo "Done! "
}

stripogg() {
    for i in *.ogg; do
        name=`echo $i | cut -d'.' -f1`
        echo "Stripping audio from ${name}.ogg "
        ffmpeg -y -i "$i" -vn -codec:a copy -map_metadata -1 "${name}.tmp.ogg" 2> /dev/null
        rm -f "$i"
        mv "${name}.tmp.ogg" "$i"
    done
    echo "Done! "
}

downloadwebsite() {
    DOMAIN=$(echo $1 | awk -F '/' '{print $1}' | awk -F '.' '{print $2,$3}' OFS=".")
    wget \
     --recursive \
     --no-clobber \
     --page-requisites \
     --html-extension \
     --convert-links \
     --restrict-file-names=windows \
     --domains $DOMAIN \
     --no-parent \
         $1
}
